# This is a basic workflow to help you get started with Actions

name: Copy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#env:
#  IMAGE_REPO: ${{ vars.IMAGE_REPO || 'zoyopei1' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      IMAGE_REPO: ${{ secrets.IMAGE_REPO || 'zoyopei' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3
      
      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag zoyopei/ingress-nginx-kube-webhook-certgen:v1.4.3 \
            registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3

